fmod PROPS-UTIL is
	protecting STRING .

	sort Prop .

	*** Proposições
    ops a b c d p q r s t u v : -> Prop [ctor] .

    op toString(_) : Prop -> String .

    eq toString(a) = "a" .
    eq toString(b) = "b" .
    eq toString(c) = "c" .
    eq toString(d) = "d" .
    eq toString(p) = "p" .
    eq toString(q) = "q" .
    eq toString(r) = "r" .
    eq toString(s) = "s" .
    eq toString(t) = "t" .
    eq toString(u) = "u" .
    eq toString(v) = "v" .
endfm